#!/usr/bin/env bash

source "$TWDE_HOME/lib/func.sh"

function init_desktop() {
  source "$TWDE_HOME/etc/theme.conf"

  if [ -n "$DESKTOP_COLOR" ];then
    xsetroot -solid "$DESKTOP_COLOR"
  fi

  xsetroot -cursor_name sb_left_arrow

  xclip=`locate_command xclip`
  echo "" | $xclip -i -selection clipboard
  echo "" | $xclip -i -selection primary
}

if [ "$1" = "start" ];then
  init_desktop
fi
