#!/usr/bin/env bash

PID="/tmp/$UID-display.pid"
CONFIG_TS="0"
CONFIG_FILE="$TWDE_HOME/etc/display.conf"

disp="$TWDE_HOME/bin/system/display"

source $TWDE_HOME/lib/func.sh

function config() {
  rm $TWDE_HOME/var/display.info 2>/dev/null

  if [ -f "$CONFIG_FILE" ];then
    $disp read_config < "$CONFIG_FILE"
  fi
}

function restore_screen() {
  autorandr -l twde
}

function save_screen() {
  autorandr --force -s twde
}

function refresh_wm() {

  echo "turn disconnected screens off"
  turnoff_disconnected

  echo "restore all windows"
  $TWDE_HOME/libexec/restore_windows

  echo "restart wm"
  $TWDE_HOME/libexec/init.d/wm_fvwm restart
}

function turnoff_disconnected() {
  xrandr | while read -r line ;do
    if [[ "$line" =~ ^(.*)\ disconnected ]];then
      dev="${BASH_REMATCH[1]}"
      echo xrandr --output $dev --off
    fi
  done
}

function trigger_event() {
  sleep 1

  local ts=`epochtime`
  local td=$(( "$ts" - "$CONFIG_TS" ))

  CONFIG_TS="$ts"
  if [ "$td" -lt 3 ];then
    echo "postpone the change"
    return
  fi

  refresh_wm
}

function monitor() {
  echo "start monitoring display changes"

  xev -root -event randr | while read -r line ;do
    if [[ "$line" =~ ^subtype\ XRROutputChangeNotifyEvent ]];then
      evt=$line

    elif [ -n "$evt" ];then
      if [[ "$line" =~ ^output\ (.*),\ crtc.*mode\ (.*)\  ]];then
        out="${BASH_REMATCH[1]}"
        mode="${BASH_REMATCH[2]}"
        trigger_event "$out" "$mode"

      elif [[ "$line" =~ ^output\ (.*),\ crtc.*mode\ None  ]];then
        out="${BASH_REMATCH[1]}"
        mode=""
        trigger_event "$out" "$mode"

      fi
 
    elif [ "$line" = "" ];then
      evt=""
    fi
  done
}

if [ "$1" = "start" ];then
  #restore_screen
  config
  #sleep 1
  #monitor&
  #echo "$!" > $PID

elif [ "$1" = "stop" ];then
  pkill -P `cat $PID`
  #save_screen

elif [ "$1" = "config" ];then
  config
  refresh_wm

fi
