#!/usr/bin/env bash

PIDFILE="/tmp/$UID-ge.pid"

function cleanup() {
  rm "$PIDFILE"
}


function make_ge_config() {
  while IFS= read -r LINE ;do
    IFS=$'\t';V=(${LINE});IFS=
    KEYS="${V[0]}"
    EXEC="${V[1]}"
    echo -e "\"$EXEC\"\n  $KEYS"
  done < "$1" > "$2"
}

function process() {
  #trap restart_xk USR1
  #trap stop_xk INT TERM
  trap cleanup EXIT

  main_loop
}

function main_loop() {
  IFS_OLD="$IFS"
  $TWDE_HOME/libexec/gesture_helper | while IFS= read -r line ;do
    if [ "$line" = "SCROLL_UP" ];then
      xdotool click 4
    fi
    if [ "$line" = "SCROLL_DOWN" ];then
      xdotool click 5
    fi
  done
}

if [ "$1" = "stop" ];then
  PID=`cat $PIDFILE`
  kill "$PID" 2>/dev/null
  exit 0
elif [ -f "$PIDFILE" ];then
  echo "running already"
  echo "restart|stop"
  exit 1
else
  process&
  echo "$!" > "$PIDFILE"
fi
