#!/usr/bin/env bash

PID="/tmp/$UID-hotkeys.pid"
CFG="$TWDE_HOME/var/xbindkeys"

. $TWDE_HOME/lib/func.sh

function config() {
  echo "configure hotkeys"
  $TWDE_HOME/libexec/menu2xbindkeys
}

function start() {
  config
  xbindkeys -n -f "$CFG" &
  echo "$!" > $PID
}

function stop() {
  kill `cat $PID`
}

if [ "$1" = "start" ];then
  start
fi
if [ "$1" = "stop" ];then
  stop
fi
