#!/usr/bin/env bash

keyboard=$TWDE_HOME/bin/system/keyboard
touchpad=$TWDE_HOME/bin/system/touchpad
mouse=$TWDE_HOME/bin/system/mouse

PID="/tmp/$UID-input.pid"
CONFIG_TS="0"

CFG_KEYBOARD="$TWDE_HOME/etc/keyboard.conf"
CFG_TOUCHPAD="$TWDE_HOME/etc/touchpad.conf"
CFG_MOUSE="$TWDE_HOME/etc/mouse.conf"

source $TWDE_HOME/lib/func.sh

function config() {
  local ts=`epochtime`
  local td=$(( "$ts" - "$CONFIG_TS" ))

  CONFIG_TS="$ts"
  if [ "$td" -lt 3 ];then
    echo "postpone the change"
    return
  fi

  if [ -f "$CFG_KEYBOARD" ];then
    echo "configure keyboard settings"
    $keyboard read_config < "$CFG_KEYBOARD"
  fi

  if [ -f "$CFG_TOUCHPAD" ];then
    echo "configure touchpad settings"
    $touchpad read_config < "$CFG_TOUCHPAD"
  fi

  if [ -f "$CFG_MOUSE" ];then
    echo "configure mouse settings"
    $mouse read_config < "$CFG_MOUSE"
  fi

}

function monitor() {
  echo "start monitoring keyboard changes"

  xprop -spy -root | while read -r line ;do
    if [[ $line =~ ^_XKB_RULES_NAMES ]] ;then
      sleep 1
      config
    fi
  done
}

function start_input() {
  config
  echo "$!" > $PID
}

function stop_input() {
  pkill -P `cat $PID`
}

if [ "$1" = "start" ];then
  start_input

elif [ "$1" = "stop" ];then
  stop_input

elif [ "$1" = "config" ];then
  config
fi
