#!/usr/bin/env bash

keyboard=$TWDE_HOME/bin/system/keyboard
touchpad=$TWDE_HOME/bin/system/touchpad
mouse=$TWDE_HOME/bin/system/mouse

PID="/tmp/$UID-input.pid"
CONFIG_STATUS="$TWDE_VAR/input.configured"

CFG_KEYBOARD="$TWDE_HOME/etc/keyboard.conf"
CFG_TOUCHPAD="$TWDE_HOME/etc/touchpad.conf"
CFG_MOUSE="$TWDE_HOME/etc/mouse.conf"

source $TWDE_HOME/lib/func.sh

function config() {
  local ft=`file_mtime "$CONFIG_STATUS"`
  local et=`epochtime`
  local dt=$(( "$et" - "$ft" ))

  if [ "$dt" -le 3 ];then
    echo "configure already, postpone"
    touch "$CONFIG_STATUS"
    return
  fi

  sleep 1

  if [ -f "$CFG_KEYBOARD" ];then
    echo "configure keyboard settings"
    $keyboard read_config < "$CFG_KEYBOARD"
  fi

  if [ -f "$CFG_TOUCHPAD" ];then
    echo "configure touchpad settings"
    $touchpad read_config < "$CFG_TOUCHPAD"
  fi

  if [ -f "$CFG_MOUSE" ];then
    echo "configure mouse settings"
    $mouse read_config < "$CFG_MOUSE"
  fi

  touch "$CONFIG_STATUS"
}

function monitor() {
  echo "start monitoring input device changes"

  xprop -spy -root | while read -r line ;do
    if [[ $line =~ ^_XKB_RULES_NAMES ]] ;then
      config
    fi
  done
}

function start_input() {
  config
  monitor&
  echo "$!" > $PID
}

function stop_input() {
  pkill -P `cat $PID`
}

if [ "$1" = "start" ];then
  start_input

elif [ "$1" = "stop" ];then
  stop_input

elif [ "$1" = "config" ];then
  config

fi
