#!/usr/bin/env bash

PID="/tmp/$UID-keyboard.pid"
B=`realpath "$0"`

. $TWDE_HOME/lib/func.sh

function config() {
  echo "configure keyboard settings"

  . $TWDE_HOME/etc/keyboard.conf

  if [ -n "$REPEAT_DELAY" ] && [ -n "$REPEAT_RATE" ];then
    echo "set delay [$REPEAT_DELAY] rate [$REPEAT_RATE]"
    xset r rate $REPEAT_DELAY $REPEAT_RATE
  fi

  if [ -n "$MODEL" ] && [ -n "$LAYOUT" ];then
    echo "set layout [$LAYOUT] model [$MODEL]"

    setxkbmap -layout "$LAYOUT" -model "$MODEL"
  fi

  if [ -f "$HOME/.Xmodmap" ];then
    echo "map keys from Xmodmap"
    xmodmap $HOME/.Xmodmap
  fi

  xset b off
}

function monitor() {
  echo "start monitoring keyboard changes"

  xprop -spy -root | while read -r line ;do
    if [[ $line =~ ^_XKB_RULES_NAMES ]] ;then
      sleep 2
      config
    fi
  done
}

function start() {
  config
  monitor&
  echo "$!" > $PID
}

function stop() {
  pkill -P `cat $PID`
}

if [ "$1" = "start" ];then
  start

elif [ "$1" = "stop" ];then
  stop

elif [ "$1" = "config" ];then
  config

fi
