#!/usr/bin/env bash

PID="/tmp/$UID-keyboard.pid"
CONFIG_TS="0"
CONFIG_FILE="$TWDE_HOME/etc/keyboard.conf"

source $TWDE_HOME/lib/func.sh

function config() {
  local ts=`epochtime`
  local td=$(( "$ts" - "$CONFIG_TS" ))

  CONFIG_TS="$ts"
  if [ "$td" -lt 3 ];then
    echo "postpone the change"
    return
  fi

  if ! [ -f "$CONFIG_FILE" ];then
    echo "no config $CONFIG_FILE found"
    return
  fi

  echo "configure keyboard settings"

}

function monitor() {
  echo "start monitoring keyboard changes"

  xprop -spy -root | while read -r line ;do
    if [[ $line =~ ^_XKB_RULES_NAMES ]] ;then
      sleep 1
      config
    fi
  done
}

function start() {
  config
  monitor&
  echo "$!" > $PID
}

function stop() {
  pkill -P `cat $PID`
}

if [ "$1" = "start" ];then
  start

elif [ "$1" = "stop" ];then
  stop

elif [ "$1" = "config" ];then
  config

fi
