#!/bin/bash

echo "configure mouse"

function monitor() {
  echo "start monitoring device changes"

  xprop -spy -root | while read -r line ;do
    if [[ $line =~ ^_XKB_RULES_NAMES ]] ;then
      sleep 1
      config
    fi
  done
}

function start() {
  config
  monitor&
  echo "$!" > $PID
}

function stop() {
  pkill -P `cat $PID`
}

if [ "$1" = "start" ];then
  start

elif [ "$1" = "stop" ];then
  stop

elif [ "$1" = "config" ];then
  config

fi
