#!/usr/bin/env bash

function control() {
  if [ "$1" = "up" ];then
    pactl -- set-sink-volume 0 +10%
  elif [ "$1" = "down" ];then
    pactl -- set-sink-volume 0 -10%
  elif [ "$1" = "mute" ];then
    pactl -- set-sink-mute 0 toggle

    #NOW=`pactl -- get-sink-mute 0`
  fi
  read_volume
}

function list_outputs() {
  pactl list short sinks | while read -r line ;do
    if [[ "$line" =~ ^([0-9]+)\	([^	]+) ]];then
      dev_name="${BASH_REMATCH[2]}"
      echo "$dev_name"
    fi
  done
}

function change_output() {
  dev_name="$1"
  [ "$dev_name" = "default" ] && dev_name="0"
  if [ "$2" = "volume_to" ];then
    pactl -- set-sink-volume "$dev_name" "$3%"
  fi
}

function make_output() {
  dev_name="$1"
  [ "$dev_name" = "default" ] && dev_name="0"
  if [ "$2" = "default" ];then
    pactl -- set-default-sink "$dev_name"
  fi
}

function show_default_output() {
  pactl -- get-default-sink
}

function show_output() {
  dev_name="$1"
  [ -z "$dev_name" ] && dev_name="0"
  [ "$dev_name" = "default" ] && dev_name="0"

  if [ "$2" = "volume" ];then
   pactl -- get-sink-volume "$dev_name" | while read -r line ;do
    if [[ "$line" =~ ^Volume:.*\ ([0-9]+)% ]];then
      dev_name="${BASH_REMATCH[1]}"
      echo "$dev_name"
    fi
  done
  fi
}

function play_sample() {
  aplay /usr/share/sounds/alsa/Front_Right.wav
}

function usage() {
  echo "audio"
  echo "audio list_outputs"
  echo "audio change_output [out] volume_to"
  echo "audio make_output [out] default"
  echo "audio show_output [out] volume"
  echo "audio show_default_output"
  echo "audio play_sample"

  exit 1
}

if [ -z "$1" ];then
  usage
else
  "$1" "$2" "$3" "$4"
fi
