#!/usr/bin/env bash

function show_devices() {
  bluetoothctl devices | while read -r line ;do
    if [[ "$line" =~ ^Device\ ([0-9A-Z:]+) ]];then
      dev=${BASH_REMATCH[1]}
      bluetoothctl info $dev
    fi
  done
}

function usage() {
  echo "power"
  echo "power show_battery_info"
  echo "power suspend"

  exit 1
}

if [ -z "$1" ];then
  usage
else
  "$1" "$2" "$3" "$4"
fi
