#!/bin/bash

if [ -z "$WIDGET_MODE" ];then
  export GEOMETRY="22x3"
  exec $TWDE_HOME/bin/show-widget "$0"
fi

source $TWDE_HOME/lib/func.sh

function display() {
  source <($TWDE_HOME/bin/system/power print_config)
  
  if [ "$CURRENT_VALUE" -le 20 ];then
    echo -e "\e[31mbattery: $CURRENT_VALUE%\e[0m"
  else
    echo "battery: $CURRENT_VALUE"
  fi
  echo " profle: $CURRENT_PROFILE"
}

cursor_off
while [ 1 ];do
  S=`display`
  echo -e "\e[H\e[2J\e[3J$S"
  sleep 15
done
