#!/bin/bash

if [ -z "$WIDGET_MODE" ];then
  export GEOMETRY="22x3"
  exec $TWDE_HOME/bin/show-widget "$0"
fi

source $TWDE_HOME/lib/func.sh

function display() {
  $TWDE_HOME/bin/system/power battery_status
  $TWDE_HOME/bin/system/power show_current_profile
}

cursor_off
while [ 1 ];do
  S=`display`
  echo -e "\e[H\e[2J\e[3J$S"
  sleep 15
done
