#!/bin/bash

if [ -z "$WIDGET_MODE" ];then
  export GEOMETRY="22x11"
  exec $TWDE_HOME/bin/show-widget "$0"
fi

source $TWDE_HOME/lib/func.sh

function display() {
  date +%x\ \ \ \ \ \ \ %H:%M
  echo "--------------------"
  cal
}

cursor_off
while [ 1 ];do
  S=`display`
  echo -e "\e[H\e[2J\e[3J$S"
  sleep 15
done
