#!/usr/bin/env bash

B=`realpath "$0"`

function make_display_menu() {
  for DD in `control display list_screens` ;do
    echo "AddToMenu DynamicDisplayMenu \"$DD\" Exec control display turn_screen $DD on"
  done
}


function init() {
  cat << EOF
DestroyMenu DynamicDisplayMenu
AddToMenu DynamicDisplayMenu DynamicPopUpAction CreateDisplayMenu

DestroyFunc CreateDisplayMenu
AddToFunc CreateDisplayMenu
+ I DestroyMenu recreate DynamicDisplayMenu
+ I PipeRead '$B make_display_menu'
EOF
}

function display() {
  cat << EOF
*RightPanel: (3x1, Id DisplayInfo, Title "display" Action (Mouse 1) Menu DynamicDisplayMenu)
*RightPanel: (1x1, Title "-", Action (Mouse 1) "Exec $B brightness_down", ActiveColorset 12, Frame 0)
*RightPanel: (1x1, Title "+"  , Action (Mouse 1) "Exec $B brightness_up", ActiveColorset 12, Frame 0)
*RightPanel: (1x1, Title "o", Action (Mouse 1) Scroll 0 3, ActiveColorset 12, Frame 0)
EOF
}

function start() {
  echo "$B starting"
  show_screen_info
}

function stop() {
  echo "$B stopping"
}

function show_screen_info() {
  V=`control display show_screen default brightness`
  FvwmCommand "SendToModule RightPanel ChangeButton DisplayInfo Title \"dis:$V\""
}

function brightness_up() {
  V=`control display change_screen default brightness_up`
  FvwmCommand "SendToModule RightPanel ChangeButton DisplayInfo Title \"dis:$V\""
}

function brightness_down() {
  V=`control display change_screen default brightness_down`
  FvwmCommand "SendToModule RightPanel ChangeButton DisplayInfo Title \"dis:$V\""
}

$1 $2 $3 $4
