#!/usr/bin/env bash

PID="/tmp/$UID-widget-power.pid"
B=`realpath "$0"`

function init() {
  cat << EOF
EOF
}

function display() {
  cat << EOF
*RightPanel: (3x1, Id PowerInfo, Title "Power")
EOF
}

function start() {
  echo "$B starting"
  process&
  echo "$!" > $PID
}

function stop() {
  echo "$B stopping"
  kill `cat $PID`
}

function process() {
  while [ 1 ];do
    source <(control power show_battery_info)
    FvwmCommand "SendToModule RightPanel ChangeButton PowerInfo Title \"$status:$value\""
    sleep 10
  done
}

$1 $2 $3 $4
