#!/usr/bin/env bash

B=`realpath "$0"`

function make_audio_menu() {
  for DD in `control audio list_outputs` ;do
    echo "AddToMenu DynamicAudioMenu \"$DD\" Exec control audio make_output $DD default;$B show_output_info"
  done
}

function init() {
  cat << EOF
DestroyMenu DynamicAudioMenu
AddToMenu DynamicAudioMenu DynamicPopUpAction CreateAudioMenu

DestroyFunc CreateAudioMenu
AddToFunc CreateAudioMenu
+ I DestroyMenu recreate DynamicAudioMenu
+ I PipeRead '$B make_audio_menu'
EOF
}

function display() {
  cat << EOF
*RightPanel: (3x1, Id VolumeInfo, Title "volume" Action (Mouse 1) Menu DynamicAudioMenu
*RightPanel: (1x1, Title "-", Action (Mouse 1) "Exec $B volume_down", ActiveColorset 12, Frame 0)
*RightPanel: (1x1, Title "+"  , Action (Mouse 1) "Exec $B volume_up", ActiveColorset 12, Frame 0)
*RightPanel: (1x1, Title "o", Action (Mouse 1) "Exec $B volume_mute", ActiveColorset 12, Frame 0)
EOF
}

function start() {
  echo "$B starting"
  show_output_info
}

function stop() {
  echo "$B stopping"
}

function show_output_info() {
  V=`control audio show_output default volume`
  FvwmCommand "SendToModule RightPanel ChangeButton VolumeInfo Title \"vol:$V\""
}

function volume_up() {
  V=`control audio change_output default volume_up`
  FvwmCommand "SendToModule RightPanel ChangeButton VolumeInfo Title \"vol:$V\""
}

function volume_down() {
  V=`control audio change_output default volume_down`
  FvwmCommand "SendToModule RightPanel ChangeButton VolumeInfo Title \"vol:$V\""
}

function volume_mute() {
  V=`control audio change_output default volume_mute`
  FvwmCommand "SendToModule RightPanel ChangeButton VolumeInfo Title \"vol:$V\""
}

$1 $2 $3 $4
