#!/bin/perl

use Time::HiRes qw(time);

$EVENT_TS=0;

sub window_events {
  open(WIN, "xev -root -event substructure -event focus |");

  $LAST_EVENT="";

  while(<WIN>) {
    chomp();
    if ($_ =~ /^MapNotify/ || $_ =~ /^DestroyNotify/) {
      $LAST_EVENT = $_;
    }
    elsif ($_ =~ /^FocusIn/) {
      $LAST_EVENT = $_;
    }
    elsif ($LAST_EVENT ne "") {
      if ($_ eq "") {
        $LAST_EVENT = "";
      }
      else {
        process_event("$LAST_EVENT $_");
      }
    }
  }
  close(WIN);
}

sub process_event {
  my ($e) = @_;
  my $t = time();
  my $d = $t - $EVENT_TS;

  if ($e =~ /NotifyPointerRoot/ && $d > 0.1) {
    focus_event();
  }
  elsif ($e =~ /NotifyNonlinearVirtual/ && $d > 0.1) {
    focus_event();
  }

  $EVENT_TS = $t;
}

sub focus_event {
  open(FIN, "xdotool getmouselocation |");
  while(<FIN>) {
    chomp();
    print("x:$_\n");
  }
  close(FIN);

}

window_events();
