#!/bin/perl

use utf8;
use Text::vFile::asData;
use Text::vCard;
use Data::Dumper;

binmode(STDOUT, ":utf8");

$BASE=".";

sub process_card {
  my ($f) = @_;
  my @lines = ();

  open(CIN, '<:encoding(UTF-8)', "$f");
  while(<CIN>) {
    chomp();
    push(@lines, $_);
  }
  close(CIN);

  my $data = Text::vFile::asData->new->parse_lines(@lines);


  my $item = $data->{objects}[0];
  my $props = $item->{properties};

  my $card = Text::vCard->new({ 'asData_node' => $props });
  my $fullname = $card->fullname();
  my $note = $card->get_simple_type('note');

  if ($fullname ne "") {
    print("$fullname\t$f\n");
  }
  else {
    print("UNKNOWN\t$f\n");
  }
}

sub process_all {
  open(FIN, "find $BASE -type f -name '*vcf' |");
  while(<FIN>) {
    chomp();
    if (-f $_) {
      process_card($_);
    }
  }
  close(FIN);
}

process_all();
