#!/usr/bin/env bash

function usage() {
  echo "prepareconf [template] [config...]"
  exit 1
}

SRC="$1"
CFG="$2"

[ -z "$CFG" ] && usage

shift
for CFG in $@ ;do
  if [ -f "$CFG" ];then
    . "$CFG"
  fi
done

export PATH="$TWDE_HOME/libexec:$PATH"
while IFS= read -r LINE ;do
  L="${LINE//\"/\\\"}"
  eval "R=\"$L\"" || (echo "$L" >/dev/stderr ;exit 1)
  echo "$R"
done < "$SRC"
