#!/usr/bin/env perl

$TWDE_HOME = $ENV{'TWDE_HOME'};
$TWDE_VAR = $ENV{'TWDE_VAR'};
$CFG_FILE = "$TWDE_VAR/widgets.saved";

sub wininfo {
	my ($WINID) = @_;
	my $GEO="";
	open(WIN, "xwininfo -id $WINID |");
	while(<WIN>) {
		chomp();
		if (m/^  \-geometry (.*?)$/) {
			$GEO=$1;
		}
	}
	close(WIN);
	return $GEO;
}

sub list_widgets {
	my $WINID="";
	my $COMMAND="";
	my $CLASS="";

	open(IN, "xlsclients -l |");
	open(OUT, "> $CFG_FILE");

	while(<IN>) {
		chomp();
		if (m/^Window (.*?):$/) {
			$WINID=$1;
		}
		elsif (m/^  Command:  (.*?)$/) {
			$COMMAND=$1;
		}
		elsif (m/^  Instance\/Class:  (.*?)$/) {
			$CLASS=$1;
			if ($CLASS eq "TWDEWidget/TWDEWidget" && $COMMAND =~ m/\-e.*'(.*?)'$/) {
				$CMD=$1;
				$GEO=wininfo($WINID);

				print(OUT "$CMD\t$GEO\n");
			}
		}

	}

	close(IN);
	close(OUT);
}

list_widgets();
