#!/usr/bin/env bash

[ -z "$REQUEST" ] && exec $TWDE_HOME/bin/hsh $0

disp=$TWDE_HOME/bin/system/display

INFO_CACHE="$TWDE_VAR/display.info"
CFG_FILE="$TWDE_HOME/etc/display.conf"

function get_display_info() {
  if [ -f "$INFO_CACHE" ];then
    cat "$INFO_CACHE"
  else
    xrandr > "$INFO_CACHE"
  fi
}

function get_val() {
  env | while read -r line ;do
    if [[ "$line" =~ ^(.*)=(.*)$ ]];then
      name="${BASH_REMATCH[1]}"
      val="${BASH_REMATCH[2]}"
      if [ "$name" = "$1" ];then
        echo "$val"
      fi
    fi
  done
}

function get_brightness() {
  $disp show_screen default brightness
}

function get_gamma() {
  $disp show_screen default gamma
}

function list_active_devs() {
  get_display_info | while read -r DD ;do
    if [[ "$DD" =~ ^(.*)\ connected\  ]];then
      last_dev="${BASH_REMATCH[1]}"

    fi

    if [[ "$DD" =~ ^([0-9]+)x([0-9]+).*\*  ]];then
      echo "$last_dev"
    fi

  done
}

function list_devs() {
  get_display_info | while read -r DD ;do
    if [[ "$DD" =~ ^(.*)\ connected\  ]];then
      dev="${BASH_REMATCH[1]}"

      echo "$dev"
    fi
  done
}

function list_displays() {
  for DD in `list_active_devs` ;do
    ACTIVE_DEVS="$ACTIVE_DEVS $DD"
  done

  get_display_info | while read -r DD ;do
    if [[ "$DD" =~ ^(.*)\ connected\  ]];then
      dev="${BASH_REMATCH[1]}"
      res="${BASH_REMATCH[2]}"

      if [ -n "$last_dev" ];then
        echo "</select>"

        echo "position: "
        echo "<select name=\"pos_$dev\">"
        echo "  <option value=\"right\">left of</option>"
        echo "  <option value=\"left\">right of</option>"
        echo "  <option value=\"below\">above</option>"
        echo "  <option value=\"above\">below</option>"
        echo "</select>"
      fi

      echo "<h3>$DD</h3>"
      echo "<select name=\"mode_$dev\">"
      echo "  <option value=\"off\">off</option>"
 
      last_dev="$DD"
    fi

    if [[ "$DD" =~ ^([0-9]+)x([0-9]+).*\*  ]];then
      w="${BASH_REMATCH[1]}"
      h="${BASH_REMATCH[2]}"

      echo "<option selected value=\"${w}x${h}\">${w}x${h}</option>"

    elif [[ "$DD" =~ ^([0-9]+)x([0-9]+)  ]];then
      w="${BASH_REMATCH[1]}"
      h="${BASH_REMATCH[2]}"

      echo "<option value=\"${w}x${h}\">${w}x${h}</option>"
    fi

  done
  echo "</select>"
}

function display_values() {
  BRIGHTNESS=`get_brightness`
  [ -z "$BRIGHTNESS" ] && BRIGHTNESS="100"

  GAMMA=`get_gamma`
  [ -z "$GAMMA" ] && GAMMA="1.0"


cat << EOF
<html>
  <head><title>Display Settings Panel</title></head>
  <body>
    <h1>Display Settings</h1>
    <form>

      `list_displays`

      <h3>Brightness:</h3>

      <button name="action" value="brightness_minus">[ - </button>
      <input name="brightness" value="$BRIGHTNESS" size="4"></input>
      <button name="action" value="brightness_plus"> + ]</button>

      <h3>Gamma:</h3>

      <input name="gamma" value="$GAMMA" size="4"></input>

      <hr>
      <center>
        <button name="action" value="refresh">[ Refresh ]</button>
        <button name="exit">[ Close]</button>
        <button name="action" value="apply">[ Apply ]</button>
      </center>
    </form>
  </body>
</html>
EOF
}

function update_brightness() {
  if [ -n "$REQUEST_brightness" ];then
    $disp change_screen default brightness_to "$REQUEST_brightness" >/dev/null
  fi
}

function update_gamma() {
  if [ -n "$REQUEST_gamma" ];then
    $disp change_screen default gamma_to "$REQUEST_gamma" >/dev/null
  fi
}

function save_values() {
  cat << EOF > $CFG_FILE
GAMMA=$REQUEST_gamma
BRIGHTNESS=$REQUEST_brightness
EOF

}

function update_values() {
  local last_dev=""
  for DD in `list_devs` ;do
    mode=`get_val "REQUEST_mode_$DD"`
    pos=`get_val "REQUEST_pos_$DD"`

    if [ -n "$mode" ];then
      if [ "$mode" = "off" ];then
        $disp turn_screen "$DD" off
      else
        $disp change_screen "$DD" resolution_to "$mode"
      fi
    fi

    if [ "$pos" = "right" ];then
      $disp place_screen "$DD" right_of "$last_dev"

    elif [ "$pos" = "left" ];then
      $disp place_screen "$DD" left_of "$last_dev"

    elif [ "$pos" = "above" ];then
      $disp place_screen "$DD" above "$last_dev"

    elif [ "$pos" = "below" ];then
      $disp place_screen "$DD" below "$last_dev"

    fi

    last_dev="$DD"
  done
}

if [ "$REQUEST_action" = "apply" ];then
  save_values
  update_values
  update_brightness
  display_values

elif [ "$REQUEST_action" = "brightness_plus" ];then
  $disp change_screen default brightness_up >/dev/null
  display_values

elif [ "$REQUEST_action" = "brightness_minus" ];then
  $disp change_screen default brightness_down >/dev/null
  display_values
else

  if [ "$REQUEST_action" = "refresh" ];then
    rm "$INFO_CACHE" 2>/dev/null
  fi
  update_brightness
  update_gamma
  display_values

fi
