#!/usr/bin/env bash

[ -z "$REQUEST" ] && exec $TWDE_HOME/bin/hsh $0

function get_val() {
  env | while read -r line ;do
    if [[ "$line" =~ ^(.*)=(.*)$ ]];then
      name="${BASH_REMATCH[1]}"
      val="${BASH_REMATCH[2]}"
      if [ "$name" = "$1" ];then
        echo "$val"
      fi
    fi
  done
}

function get_brightness() {
  brightnessctl -m | while read -r DD ;do
    if [[ "$DD" =~ ,([0-9]+)% ]];then
      echo "${BASH_REMATCH[1]}"
    fi
  done
}

function list_active_devs() {
  xrandr | while read -r DD ;do
    if [[ "$DD" =~ ^(.*)\ connected\  ]];then
      last_dev="${BASH_REMATCH[1]}"

    fi

    if [[ "$DD" =~ ^([0-9]+)x([0-9]+).*\*  ]];then
      echo "$last_dev"
    fi

  done
}

function list_devs() {
  xrandr | while read -r DD ;do
    if [[ "$DD" =~ ^(.*)\ connected\  ]];then
      dev="${BASH_REMATCH[1]}"

      echo "$dev"
    fi
  done
}

function list_displays() {
  for DD in `list_active_devs` ;do
    ACTIVE_DEVS="$ACTIVE_DEVS $DD"
  done

  xrandr | while read -r DD ;do
    if [[ "$DD" =~ ^(.*)\ connected\  ]];then
      dev="${BASH_REMATCH[1]}"
      res="${BASH_REMATCH[2]}"

      if [ -n "$last_dev" ];then
        echo "</select>"

        echo "position: "
        echo "<select name=\"pos_$dev\">"
        echo "  <option value=\"right\">left of</option>"
        echo "  <option value=\"left\">right of</option>"
        echo "  <option value=\"below\">above</option>"
        echo "  <option value=\"above\">below</option>"
        echo "</select>"
      fi

      echo "<h3>$DD</h3>"
      echo "<select name=\"mode_$dev\">"
      echo "  <option value=\"off\">off</option>"
 
      last_dev="$DD"
    fi

    if [[ "$DD" =~ ^([0-9]+)x([0-9]+).*\*  ]];then
      w="${BASH_REMATCH[1]}"
      h="${BASH_REMATCH[2]}"

      echo "<option selected value=\"${w}x${h}\">${w}x${h}</option>"

    elif [[ "$DD" =~ ^([0-9]+)x([0-9]+)  ]];then
      w="${BASH_REMATCH[1]}"
      h="${BASH_REMATCH[2]}"

      echo "<option value=\"${w}x${h}\">${w}x${h}</option>"
    fi

  done
  echo "</select>"
}

function display_values() {
  BRIGHTNESS=`get_brightness`
  [ -z "$BRIGHTNESS" ] && BRIGHTNESS="100"

cat << EOF
<html>
  <head><title>Display Settings Panel</title></head>
  <body>
    <h1>Display Settings</h1>
    <form>

      `list_displays`

      <h3>Brighness:</h3>

      <button name="action" value="brightness_minus">[ - </button>
      <input name="brightness" value="$BRIGHTNESS" size="4"></input>
      <button name="action" value="brightness_plus"> + ]</button>

      <hr>
      <center>
        <button name="exit">[ Cancel ]</button>
        <button name="action" value="apply">[ Apply ]</button>
      </center>
    </form>
  </body>
</html>
EOF
}

function update_brightness() {
  brightnessctl s "$REQUEST_brightness%" > /dev/null
}

function update_values() {
  local last_dev=""
  for DD in `list_devs` ;do
    mode=`get_val "REQUEST_mode_$DD"`
    pos=`get_val "REQUEST_pos_$DD"`

    if [ -n "$mode" ];then
      if [ "$mode" = "off" ];then
        xrandr --output "$DD" --off
      else
        xrandr --output "$DD" --mode "$mode"
      fi
    fi

    if [ "$pos" = "right" ];then
     xrandr --output "$DD" --right-of "$last_dev"
    elif [ "$pos" = "left" ];then
     xrandr --output "$DD" --left-of "$last_dev"
    elif [ "$pos" = "above" ];then
     xrandr --output "$DD" --above "$last_dev"
    elif [ "$pos" = "below" ];then
     xrandr --output "$DD" --below "$last_dev"
    fi

    last_dev="$DD"
  done
}

if [ "$REQUEST_action" = "apply" ];then
  update_values
  update_brightness
  display_values

elif [ "$REQUEST_action" = "brightness_plus" ];then
  brightnessctl s "10%+" > /dev/null
  display_values

elif [ "$REQUEST_action" = "brightness_minus" ];then
  brightnessctl s "10%-" > /dev/null
  display_values

elif [ -n "$REQUEST_brightness" ];then
  update_brightness
  display_values

else
  display_values

fi
