#!/bin/bash

[ -z "$REQUEST" ] && exec $TWDE_HOME/bin/hsh $0

function list_models() {
  echo '<select name="model">'
  for DD in `localectl list-x11-keymap-models`;do
    if [ "$DD" = "$MODEL" ];then
      echo "<option selected>$DD</option>"
    else
      echo "<option>$DD</option>"
    fi
  done
  echo "</select>"
}

function current_config() {
  echo "REPEAT_DELAY=600"
  echo "REPEAT_RATE=25"

  localectl -l | while read -r line ;do
    if [[ "$line" =~ ^X11\ Layout:\ (.*)$ ]];then
      echo "LAYOUT=${BASH_REMATCH[1]}"
    fi
    if [[ "$line" =~ ^X11\ Model:\ (.*)$ ]];then
      echo "MODEL=${BASH_REMATCH[1]}"
    fi
  done
}

function list_layouts() {
  echo '<select name="layout">'
  for DD in `localectl list-x11-keymap-layouts`;do
    if [ "$DD" = "$LAYOUT" ];then
      echo "<option selected>$DD</option>"
    else
      echo "<option>$DD</option>"
    fi
  done
  echo "</select>"
}

function update_values() {

cat << EOF > $TWDE_HOME/etc/keyboard.conf
SWAP_FN=1
# 0 - disabled, 1 media keys, 2 function keys
FN_MODE=2
SWAP_ALT_CMD=1
REPEAT_DELAY=$REQUEST_delay
REPEAT_RATE=$REQUEST_rate
MODEL=$REQUEST_model
LAYOUT=$REQUEST_layout
EOF

  $TWDE_HOME/libexec/init.d/keyboard config > /dev/null
}

function display_values() {
  if [ -f "$TWDE_HOME/etc/keyboard.conf" ];then
    source $TWDE_HOME/etc/keyboard.conf
  else
    source <(current_config)
  fi

cat << EOF
<html>
  <head><title>Keyboard Settings Panel</title></head>
  <body>
    <h1>Keyboard Settings</h1>
    <form>
      <h3>Repeat Delay: </h3>
      <input name="delay" value="$REPEAT_DELAY"></input>

      <h3>Repeat Rate: </h3>
      <input name="rate" value="$REPEAT_RATE"></input>

      <h3>Keyboard Model: </h3>
      
      `list_models`
      layout: `list_layouts`

      <h3>Test: </h3>
      <input></input>

      <hr>
      <center>
        <button name="exit">[ Cancel ]</button>
        <button name="action" value="apply">[ Apply ]</button>
      </center>
    </form>
  </body>
</html>
EOF
}

if [ -n "$REQUEST_delay" ];then
  update_values
  display_values
else
  display_values
fi
