#!/bin/bash

if [ "$1" = "install_locales" ];then
  clear
  sudo dpkg-reconfigure locales

  exit $?
else
  [ -z "$REQUEST" ] && exec $TWDE_HOME/bin/hsh $0
fi

LOCALE_LIST_CACHE=`localectl list-locales`

function list_timezones() {
  echo '<select name="timezone">'
  for DD in `timedatectl list-timezones`;do
    if [ "$DD" = "$TIMEZONE" ];then
      echo "<option selected>$DD</option>"
    else
      echo "<option>$DD</option>"
    fi
  done
  echo "</select>"
}

function gen_local_list() {
  echo "$LOCALE_LIST_CACHE"
}

function list_locales() {
  local name="$1"
  local val="$2"

  echo "<select name=\"$name\">"
  echo "<option value=\"\">default</option>"
  for DD in `gen_local_list` ;do
    if [ "$DD" = "$val" ];then
      echo "<option selected>$DD</option>"
    else
      echo "<option>$DD</option>"
    fi
  done
  echo "</select>"
}

function update_values() {
  cat << EOF > $TWDE_HOME/etc/locale.conf
TIMEZONE="$REQUEST_timezone"
LOCALE="$REQUEST_locale"
DATETIME="$REQUEST_datetime"
NUMBER="$REQUEST_number"
EOF

}

function display_values() {
  if [ -f "$TWDE_HOME/etc/locale.conf" ];then
    source $TWDE_HOME/etc/locale.conf
  fi

  if [ -z "$TIMEZONE" ];then
    TIMEZONE=`timedatectl show -p Timezone --value`
  fi
  if [ -z "$LOCALE" ];then
    LOCALE="$LANG"
  fi

  export TZ="$TIMEZONE"
  export LANG="$LOCALE"

  if [ -n "$DATETIME" ];then
    export LC_TIME="$DATETIME"
  fi

  if [ -n "$NUMBER" ];then
    export LC_NUMERIC="$NUMBER"
  fi

cat << EOF
<html>
  <head><title>Locale Settings Panel</title></head>
  <body>
    <h1>Local Settings</h1>
    <form>
      <h3>Time Zone: </h3>
      `list_timezones`

      <h3>Default Locale: </h3>
      `list_locales locale $LOCALE`

      <button name="exec" value="$0 install_locales">add</button> - install more locales

      <br>

      <h3>Time and date format: </h3>
      `list_locales datetime $DATETIME` example: `date`

      <h3>Number format: </h3>
      `list_locales number $NUMBER` example: `printf "%'f" "12345678.123"`

      <hr>
      <center>
        <button name="exit">[ Cancel ]</button>
        <button name="action" value="apply">[ Apply ]</button>
      </center>
    </form>
  </body>
</html>
EOF
}

if [ -n "$REQUEST_timezone" ];then
  update_values
  display_values
else
  display_values
fi
