#!/bin/bash

[ -z "$REQUEST" ] && exec $TWDE_HOME/bin/hsh $0

function display_values() {
  . $TWDE_HOME/etc/keyboard.conf

cat << EOF
<html>
  <head><title>Mouse Setting Panel</title></head>
  <body>
    <h1>Mouse Settings</h1>
    <form>
      <h3>Repeat Delay: </h3>
      <input name="delay" value="$REPEAT_DELAY"></input>

      <h3>Repeat Rate: </h3>
      <input name="rate" value="$REPEAT_RATE"></input>

      <h3>Repeat Rate: </h3>
      <input name="valC" type="checkbox">$REPEAT_RATE</input>

      <hr>
      <center>
        <button name="exit">[ Cancel ]</button>
        <button name="action" value="apply">[ Apply ]</button>
      </center>
    </form>
  </body>
</html>
EOF
}

if [ "$REQUEST_action" = "apply" ];then
  display_values
else
  display_values
fi

