#!/usr/bin/env bash

[ -z "$REQUEST" ] && exec $TWDE_HOME/bin/hsh $0

CFG_FILE="$TWDE_HOME/etc/mouse.conf"
mouse="$TWDE_HOME/bin/system/mouse"

function save_values() {
  cat << EOF > $CFG_FILE
SPEED_VALUE=$REQUEST_speed
EOF
}


function display_values() {
  source <( $mouse print_config )

cat << EOF
<html>
  <head><title>Mouse Setting Panel</title></head>
  <body>
    <h1>Mouse Settings</h1>
    <form>
      <h3>Speed: </h3>

      <button name="action" value="speed_minus">[ slower </button>
      <input name="speed" value="$SPEED_VALUE" size="4"></input>
      <button name="action" value="speed_plus"> faster ]</button>

      <hr>
      <center>e
        <button name="exit">[ Cancel ]</button>
        <button name="action" value="apply">[ Apply ]</button>
      </center>
    </form>
  </body>
</html>
EOF
}

if [ "$REQUEST_action" = "apply" ];then
  save_values
  display_values

elif [ "$REQUEST_action" = "speed_plus" ];then
  SPEED=$(( $REQUEST_speed + 1 ))
  $mouse change_speed_to "$SPEED"
  display_values

elif [ "$REQUEST_action" = "speed_minus" ];then
  SPEED=$(( $REQUEST_speed - 1 ))
  $mouse change_speed_to "$SPEED"
  display_values

else
  display_values

fi

