#!/usr/bin/env bash

. $TWDE_HOME/etc/browser.conf
. $TWDE_HOME/lib/func.sh

CHROME=`type -p firefox`
[ -z "$CHROME" ] && CHROME=`type -p google-chromium`
[ -z "$CHROME" ] && CHROME=`type -p chromium`
[ -z "$CHROME" ] && CHROME=`type -p chromium-browser`
[ -z "$CHROME" ] && CHROME=`type -p chrome`

read -t "0.1" WORD

if [ -z "$WORD" ];then
  if [ -z "$1" ];then
    exec $CHROME "$HOME_URL" 2>/dev/null >/dev/null &
  else
    exec $CHROME "$1" 2>/dev/null >/dev/null &
  fi
else
  WORD=`encode_url "$WORD"`
  exec $CHROME "$SEARCH_URL$WORD" 2>/dev/null >/dev/null &
fi
