#!/usr/bin/env bash

. $TWDE_HOME/lib/func.sh

read -t "0.1" WORD

if [ -z "$WORD" ] && [ -n "$1" ];then
  WORD="$1"
fi

CFG="$TWDE_HOME/var/terminal.xrm"
prepareconf "$TWDE_HOME/lib/xterm.xrm" \
  $TWDE_HOME/etc/theme.conf \
  $TWDE_HOME/etc/terminal.conf > $CFG

xrdb -merge "$CFG"

. $TWDE_HOME/etc/manual.conf

exec xterm -geometry "${WIDTH}x${HEIGHT}" -bg "$BACKGROUND_COLOR" -fg "$FOREGROUND_COLOR" \
    -name TWDETerm -class TWDETerm -e "man_info_lookup.sh $WORD" &
