#!/usr/bin/env bash

CFG="$TWDE_HOME/var/terminal.xrm"
prepareconf "$TWDE_HOME/lib/xterm.xrm" \
  $TWDE_HOME/etc/theme.conf \
  $TWDE_HOME/etc/terminal.conf > "$CFG"

xrdb -merge "$CFG"

if [ -n "$1" ];then
  exec xterm -name TWDETerm -class TWDETerm -e "$@" &
else
  exec xterm -name TWDETerm -class TWDETerm &
fi
