#!/usr/bin/env bash

CFG="$TWDE_VAR/terminal.xrm"

$TWDE_HOME/libexec/make_config "$TWDE_HOME/lib/xterm.xrm" \
  $TWDE_HOME/etc/theme.conf \
  $TWDE_HOME/etc/terminal.conf > "$CFG"

xrdb -merge "$CFG"

if [ -n "$1" ];then
  if [ -f "$1" ];then
    CMD="$1"
    if ! [ -x "$CMD" ];then
      CMD="sh $CMD"
    fi
    exec xterm -name TWDETerm -class TWDETerm -e "$CMD ; read DD" &
  else
    exec xterm -name TWDETerm -class TWDETerm -e "$@" &
  fi
else
  exec xterm -ls -name TWDETerm -class TWDETerm &
fi
